module.exports = [
	{
		name: 'Wooden Axe',
		category: 'axe',
		durability: 25,
		choppingPower: 10,
		equippable: true,
		display: true,
		materials: [{ name: 'oak_wood', amount: 50, display: 'Oak Wood' }],
	},
	{
		name: 'Stone Axe',
		category: 'axe',
		durability: 50,
		choppingPower: 15,
		equippable: true,
		display: true,
		materials: [
			{ name: 'oak_wood', amount: 100, display: 'Oak Wood' },
			{ name: 'stone', amount: 50, display: 'Stone' },
		],
	},
	{
		name: 'Iron Axe',
		category: 'axe',
		durability: 100,
		choppingPower: 20,
		equippable: true,
		display: true,
		materials: [
			{ name: 'oak_wood', amount: 150, display: 'Oak Wood' },
			{ name: 'stone', amount: 100, display: 'Stone' },
			{ name: 'iron', amount: 50, display: 'Iron' },
		],
	},
	{
		name: 'Gold Axe',
		category: 'axe',
		durability: 75,
		choppingPower: 35,
		equippable: true,
		display: true,
		materials: [
			{ name: 'oak_wood', amount: 100, display: 'Oak Wood' },
			{ name: 'gold', amount: 100, display: 'Gold' },
		],
	},
	{
		name: 'Diamond Axe',
		category: 'axe',
		durability: 200,
		choppingPower: 50,
		equippable: true,
		display: true,
		materials: [
			{ name: 'oak_wood', amount: 200, display: 'Oak Wood' },
			{ name: 'diamond', amount: 100, display: 'Diamond' },
		],
	},
	{
		name: 'Plasma Axe',
		category: 'axe',
		durability: Infinity,
		choppingPower: Infinity,
		equippable: true,
		display: false,
		materials: [
			{
				name: 'developer_only',
				amount: 1,
				display: 'Developer Only',
			},
		],
	},
	{
		name: 'Wooden Pickaxe',
		category: 'pickaxe',
		durability: 25,
		miningPower: 10,
		equippable: true,
		display: true,
		canMine: [{ name: 'Stone', chance: 100, min: 2, max: 5 }],
		materials: [{ name: 'oak_wood', amount: 50, display: 'Oak Wood' }],
	},
	{
		name: 'Stone Pickaxe',
		category: 'pickaxe',
		durability: 50,
		miningPower: 15,
		equippable: true,
		display: true,
		canMine: [
			{ name: 'Stone', chance: 80, min: 2, max: 5 },
			{ name: 'Iron', chance: 40, min: 1, max: 3 },
		],
		materials: [
			{ name: 'oak_wood', amount: 100, display: 'Oak Wood' },
			{ name: 'stone', amount: 50, display: 'Stone' },
		],
	},
	{
		name: 'Iron Pickaxe',
		category: 'pickaxe',
		durability: 100,
		miningPower: 20,
		equippable: true,
		display: true,
		canMine: [
			{ name: 'Stone', chance: 70, min: 3, max: 6 },
			{ name: 'Iron', chance: 60, min: 2, max: 4 },
			{ name: 'Gold', chance: 35, min: 4, max: 5 },
		],
		materials: [
			{ name: 'oak_wood', amount: 150, display: 'Oak Wood' },
			{ name: 'stone', amount: 100, display: 'Stone' },
			{ name: 'iron', amount: 50, display: 'Iron' },
		],
	},
	{
		name: 'Gold Pickaxe',
		category: 'pickaxe',
		durability: 75,
		miningPower: 35,
		equippable: true,
		display: true,
		canMine: [
			{ name: 'Stone', chance: 60, min: 4, max: 7 },
			{ name: 'Iron', chance: 75, min: 3, max: 5 },
			{ name: 'Gold', chance: 55, min: 2, max: 4 },
			{ name: 'Diamond', chance: 25, min: 1, max: 2 },
		],
		materials: [
			{ name: 'oak_wood', amount: 100, display: 'Oak Wood' },
			{ name: 'gold', amount: 100, display: 'Gold' },
		],
	},
	{
		name: 'Diamond Pickaxe',
		category: 'pickaxe',
		durability: 200,
		miningPower: 50,
		equippable: true,
		display: true,
		canMine: [
			{ name: 'Stone', chance: 50, min: 5, max: 8 },
			{ name: 'Iron', chance: 85, min: 4, max: 6 },
			{ name: 'Gold', chance: 70, min: 3, max: 5 },
			{ name: 'Diamond', chance: 50, min: 2, max: 3 },
		],
		materials: [
			{ name: 'oak_wood', amount: 200, display: 'Oak Wood' },
			{ name: 'diamond', amount: 100, display: 'Diamond' },
		],
	},
];
