module.exports = {
	sword: [
		{
			name: 'Wooden Sword',
			emoji: '<:placeholder:1342629058835513354>',
			attack: 5,
			durability: 25,
			equippable: true,
			level: 1,
			materials: [{ name: 'oak_wood', amount: 50, display: 'Oak Wood' }],
		},
		{
			name: 'Stone Sword',
			emoji: '<:placeholder:1342629058835513354>',
			attack: 10,
			durability: 50,
			equippable: true,
			level: 2,
			materials: [
				{ name: 'oak_wood', amount: 100, display: 'Oak Wood' },
				{ name: 'stone', amount: 50, display: 'Stone' },
			],
		},
	],
	axe: [
		{
			name: 'Wooden Axe',
			emoji: '<:wooden_sword:1342606489436553226>',
			durability: 25,
			choppingPower: 10,
			equippable: true,
			level: 1,
			canGet: [{ name: 'oak_wood', chance: 100, min: 2, max: 5 }],
			materials: [{ name: 'oak_wood', amount: 50, display: 'Oak Wood' }],
		},
		{
			name: 'Stone Axe',
			emoji: '<:placeholder:1342629058835513354>',
			durability: 50,
			choppingPower: 15,
			equippable: true,
			level: 2,
			canGet: [{ name: 'oak_wood', chance: 100, min: 5, max: 10 }],
			materials: [
				{ name: 'oak_wood', amount: 100, display: 'Oak Wood' },
				{ name: 'stone', amount: 50, display: 'Stone' },
			],
		},
	],
	pickaxe: [
		{
			name: 'Wooden Pickaxe',
			emoji: '<:placeholder:1342629058835513354>',
			durability: 25,
			miningPower: 10,
			equippable: true,
			level: 1,
			canGet: [{ name: 'Stone', chance: 100, min: 2, max: 5 }],
			materials: [{ name: 'oak_wood', amount: 50, display: 'Oak Wood' }],
		},
		{
			name: 'Stone Pickaxe',
			emoji: '<:placeholder:1342629058835513354>',
			durability: 50,
			miningPower: 15,
			equippable: true,
			level: 2,
			canGet: [
				{ name: 'Stone', chance: 80, min: 2, max: 5 },
				{ name: 'Iron', chance: 40, min: 1, max: 3 },
			],
			materials: [
				{ name: 'oak_wood', amount: 100, display: 'Oak Wood' },
				{ name: 'stone', amount: 50, display: 'Stone' },
			],
		},
	],
	armor: [
		{
			name: 'Wooden Armor',
			emoji: '<:placeholder:1342629058835513354>',
			defense: 5,
			durability: 25,
			equippable: true,
			level: 1,
			materials: [{ name: 'oak_wood', amount: 50, display: 'Oak Wood' }],
		},
		{
			name: 'Stone Armor',
			emoji: '<:placeholder:1342629058835513354>',
			defense: 10,
			durability: 50,
			equippable: true,
			level: 2,
			materials: [
				{ name: 'oak_wood', amount: 100, display: 'Oak Wood' },
				{ name: 'stone', amount: 50, display: 'Stone' },
			],
		},
	],
};
